
export const Database = [
  {
    id: 0,
    name: "Ginger-eke Charles",
    img: "https://plus.unsplash.com/premium_photo-1688891564708-9b2247085923?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Frontend",
    about:"Combining a passion for user-centric design with a solid technical foundation, I am dedicated to crafting immersive digital experiences that captivate and delight users. ",
    Grade: 98,
  },
  {
    id: 4,
    name: "Naruto Uzumaki",
    img: "https://plus.unsplash.com/premium_photo-1681489930334-b0d26fdb9ed8?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Frontend",
    about:"Passionate frontend developer with a keen eye for detail and a knack for crafting immersive user experiences.Proficient in HTML, CSS, and JavaScript, with expertise in modern frameworks like React and Vue.js. Dedicated to staying updated on the latest trends and technologies in web development to deliver cutting-edge solutions.",
    Grade: 48,
  },
  {
    id: 3,
    name: "Gon Freecss",
    img: "https://images.unsplash.com/photo-1463453091185-61582044d556?q=80&w=2940&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Frontend",
    about: "As a frontend web developer, I thrive on the intersection of creativity and technology, constantly pushing boundaries to create visually stunning and intuitive user interfaces.",
    Grade: 53,
  },
  {
    id: 2,
    name: "Lelouch Lamperouge",
    img: "https://images.unsplash.com/photo-1544723795-3fb6469f5b39?q=80&w=2592&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Frontend",
    about: "With a deep understanding of HTML, CSS, and JavaScript, coupled with a flair for design, I specialize in transforming abstract concepts into sleek and responsive web applications.",
    Grade: 60,
  },
  {
    id: 1,
    name: "Edward Elric",
    img: "https://plus.unsplash.com/premium_photo-1666264200737-acad542a92ff?q=80&w=2728&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Frontend",
    about: "From wireframes to pixel-perfect layouts, I excel in translating design concepts into code, ensuring seamless functionality across multiple devices and browsers.",
    Grade: 67,
  },
  {
    id: 1,
    name: "Francis Eke",
    img: "https://images.unsplash.com/photo-1639747280804-dd2d6b3d88ac?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Backend",
    about: "I works tirelessly behind the scenes, ensuring that servers, databases, and application logic function seamlessly to deliver a smooth user experience. He thrives on tackling complex challenges, whether it's optimizing database queries for better performance or integrating third-party services to enhance functionality.",
    Grade: 73,
  },
  {
    id: 2,
    name: "Sasuke Uchiha",
    img: "https://plus.unsplash.com/premium_photo-1689539137236-b68e436248de?q=80&w=2942&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
    info: "Backend",
    about: "Equipped with a strong understanding of programming languages like Python, Java, or Ruby, I collaborates closely with frontend developers and designers to bring projects to life. His expertise extends to frameworks such as Django, Flask, Spring, or Ruby on Rails, allowing him to streamline development processes and deliver scalable solutions.",
    Grade: 67,
  },
  {
    id: 0,
    name: "Chukwuma James",
    img: "https://plus.unsplash.com/premium_photo-1689568126014-06fea9d5d341?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8MzN8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fHww",
    info: "Backend",
    about: " I excel in communication and teamwork, translating client requirements into technical specifications and collaborating effectively within interdisciplinary teams. With a dedication to staying updated on the latest technologies and best practices in backend development, John ensures that his projects are not only functional but also future-proof.",
    Grade: 76,
  },
  {
    id: 4,
    name: "Somto Eke",
    img: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=800&auto=format&fit=crop&q=60&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxzZWFyY2h8Mzh8fHByb2ZpbGUlMjBwaWN0dXJlfGVufDB8fDB8fHww",
    info: "Backend",
    about: "Whether optimizing in database schemas, implementing security protocols, or debugging intricate issues, my commitment to excellence shines through in every line of code he writes. As a backend web developer, I play a vital role in shaping the digital landscape, driving innovation, and delivering dynamic online experiences for users worldwide.",
    Grade: 40,
  },
  {
    id: 3,
    name: "James John",
    img: "https://images.unsplash.com/photo-1487412720507-e7ab37603c6f?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
    info: "Backend",
    about: "Hey there! I'm John, and I'm passionate about all things backend web development. Being a backend developer is like being the architect behind the scenes of a digital masterpiece. While users see the polished frontend, I'm the one making sure everything runs smoothly and efficiently on the backend.",
    Grade: 54,
  },
  {
    id: 0,
    name: " Charles joor",
    img: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
    info: "Product-Design",
    about: "As a product designer, my main focus is on understanding users' needs and translating them into intuitive and visually appealing digital products. Whether it's a website, a mobile app, or a software platform, my goal is to design solutions that make people's lives easier and more enjoyable.",
    Grade: 94,
  },
  {
    id: 2,
    name: "Mary john",
    img: "https://images.unsplash.com/photo-1494790108377-be9c29b29330?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
    info: "Product-Design",
    about: "Hi, I'm Sarah! Empathy is my superpower as a product designer. I thrive on understanding users' needs and crafting designs that truly resonate with them. It's not just about making things look good; it's about making them feel right",
    Grade: 77,
  },
  {
    id: 1,
    name: "Kelvin lamar",
    img: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
    info: "Product-Design",
    about: "Hey there, I'm Mike! Collaboration is my secret sauce as a product designer. I love bouncing ideas off teammates, working closely with developers, and bringing diverse perspectives together to create products that shine.",
    Grade: 88,
  },
  {
    id: 3,
    name: "Ifunanya Stephen",
    img: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
    info: "Product-Design",
    about: "Hi, I'm Emily! Solving puzzles is my passion as a product designer. Whether it's untangling complex user flows or refining UI elements for clarity, I thrive on finding elegant solutions to tricky design challenges",
    Grade: 66,
  },
  {
    id: 4,
    name: "Uchenna Ginger",
    img: "https://images.unsplash.com/photo-1570295999919-56ceb5ecca61?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=facearea&facepad=4&w=256&h=256&q=60",
    info: "Product-Design",
    about: "Hey, I'm Alex! Data is my best friend in product design. I'm all about testing hypotheses, analyzing user behavior, and using insights to drive design decisions. It's not just about gut feelings; it's about data-driven design at its finest",
    Grade: 59,
  },
];
